services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ajf
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy

  db: #note this line begins with two spaces
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ajf
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: